### ISSUE TITLE
Port your project for IWR6843

### ISSUE THREAD

**Issue by oualit** [lynnlilu/mmWave_reading#1]
Hello,

I have the IWR6843 and MMWAVEICBOOST and I want to do the same thing. However, it doesn't work. I would like to know if there is an easy way to adapt your program to my task or which side of the program to look at.

Thank you so much for your help!

**Comment by lynnlilu** [comment]
Hi, 

It seems you use the chip IWR6843 and a carrier board MMWAVEICBOOST to conduct the experiments. Is your outputted data from mmWave Domo Visualizer? I am not sure if the data structure of your setup is the same with mine (i.e., AWR1642BOOST only). Maybe this is the problem. 

Attached is a slide provided by TI describing the data structure of the output from mmWave Domo Visualizer. I just implement the reading process following this. Note that some descriptions of the specific number are incorrect in the slide. For more detail, you can refer to the SDK user guide.

Hope it helps.

[mmw Demo Data Structure_8_16.pdf](https://github.com/lynnlilu/mmWave_reading/files/3095441/mmw.Demo.Data.Structure_8_16.pdf)

**Comment by oualit** [comment]
Hi,

Thank you very much for your answer and your help. I confirm you I use the IWR6843 + MMWAVEICBOOST and the outputted data are from Demo Visualizer 3.1.0.  It seems now that I managed to run your program by understanding and modifying the configuration variables. The Matlab program is now launched without error.

I have now two questions for you:

- Is range_bins_num always equal to ADC_sample_num? If not, how to find its value? I read the SDK manual and I did not find mention of its presence in profileCfg, frameCfg...

- Once the program launches, how to open the processed data? I have trouble understanding the output variables.

Thanks a lot for your help. It helps me a lot to have your program to try to analyze the dat files, I did not know where to start.

![mmwave_reading](https://user-images.githubusercontent.com/49742921/56564260-006a4900-65f1-11e9-8ada-64143f983c31.PNG)

**Comment by lynnlilu** [comment]
Hi,

Sorry for the late reply. The answers are as follow.

1. Exactly. The range_bins_num always equal to ADC_sample_num.

2. The output data are all in the cell packageall. Each element in packageall is a package of the data. Each package is an n*3 cell. Each row is a category of data, which is exhibited in the first column, i.e., the tag of the data category. For the package details, the pdf that I provide to you last time or the SDK user guide would be helpful. 

Hope it helps.
